"use strict";
var DIG_main;
(function (DIG_main) {
    let flagDiv;
    function addHeader_Logo() {
        let logoImg = document.createElement("img");
        logoImg.id = "logoSize";
        logoImg.src = "assets/DIG.png";
        let logoA = document.createElement("a");
        logoA.href = "Home.html";
        let logoDiv = document.createElement("div");
        logoDiv.classList.add("item1");
        logoDiv.id = "Logo";
        logoA.appendChild(logoImg);
        logoDiv.appendChild(logoA);
        DIG_main.header.appendChild(logoDiv);
    }
    DIG_main.addHeader_Logo = addHeader_Logo;
    function addHeader_Icons() {
        let iconsSearchA = document.createElement("a");
        iconsSearchA.classList.add("fa-solid");
        iconsSearchA.classList.add("fa-magnifying-glass");
        let iconsSearchSpan = document.createElement("span");
        iconsSearchSpan.id = "search";
        let iconsMenuA = document.createElement("a");
        iconsMenuA.classList.add("fa-solid");
        iconsMenuA.classList.add("fa-bars");
        let iconsMenuSpan = document.createElement("span");
        iconsMenuSpan.id = "menu";
        let iconsDiv = document.createElement("div");
        iconsDiv.classList.add("icons");
        iconsSearchSpan.appendChild(iconsSearchA);
        iconsMenuSpan.appendChild(iconsMenuA);
        iconsDiv.appendChild(iconsSearchSpan);
        iconsDiv.appendChild(iconsMenuSpan);
        DIG_main.header.appendChild(iconsDiv);
    }
    DIG_main.addHeader_Icons = addHeader_Icons;
    function addHeader_Language(_screenTypeShort) {
        DIG_main.deFlag = document.createElement("img");
        DIG_main.deFlag.src = "assets/german.png";
        DIG_main.deFlag.alt = "DE";
        DIG_main.deFlag.classList.add("flag");
        DIG_main.deFlag.id = "DE_" + _screenTypeShort;
        DIG_main.deFlag.addEventListener("click", DIG_main.handleEvent);
        DIG_main.enFlag = document.createElement("img");
        DIG_main.enFlag.src = "assets/english.png";
        DIG_main.enFlag.alt = "EN";
        DIG_main.enFlag.classList.add("flag");
        DIG_main.enFlag.id = "EN_" + _screenTypeShort;
        DIG_main.enFlag.addEventListener("click", DIG_main.handleEvent);
        DIG_main.enFlag.style.filter = "grayscale(100%)";
        DIG_main.enFlag.style.webkitFilter = "grayscale(100%)";
        if (_screenTypeShort == "v") {
            flagDiv = document.createElement("div");
            flagDiv.id = "languageDiv";
            flagDiv.appendChild(DIG_main.deFlag);
            flagDiv.appendChild(DIG_main.enFlag);
        }
        else if (_screenTypeShort == "h") {
            let flagSpan = document.createElement("span");
            flagSpan.id = "language";
            flagDiv = document.createElement("div");
            flagDiv.classList.add("item2");
            flagSpan.appendChild(DIG_main.deFlag);
            flagSpan.appendChild(DIG_main.enFlag);
            flagDiv.appendChild(flagSpan);
            DIG_main.header.appendChild(flagDiv);
        }
    }
    DIG_main.addHeader_Language = addHeader_Language;
    function addHeader_Search() {
        let searchInput = document.createElement("input");
        searchInput.type = "text";
        searchInput.name = "searchbar";
        searchInput.classList.add("inputSearch");
        let searchI = document.createElement("i");
        searchI.classList.add("fa-solid");
        searchI.classList.add("fa-magnifying-glass");
        let searchSpan = document.createElement("span");
        searchSpan.classList.add("searchBar");
        let searchDiv = document.createElement("div");
        searchDiv.classList.add("item3");
        searchSpan.appendChild(searchInput);
        searchSpan.appendChild(searchI);
        searchDiv.appendChild(searchSpan);
        DIG_main.header.appendChild(searchDiv);
    }
    DIG_main.addHeader_Search = addHeader_Search;
    function addHeader_Navigation(_data) {
        //Navigation Infos
        let infosA = document.createElement("a");
        infosA.classList.add("mI_Text");
        infosA.href = "Infos.html";
        infosA.innerText = "Infos";
        let infosLi = document.createElement("li");
        infosLi.classList.add("mainItem");
        infosLi.id = "Infos";
        infosLi.appendChild(infosA);
        let historyA = document.createElement("a");
        historyA.href = "Infos.html";
        historyA.innerText = "Geschichte der DIG";
        let historyLi = document.createElement("li");
        historyLi.id = "Geschichte";
        historyLi.appendChild(historyA);
        let contactsA = document.createElement("a");
        contactsA.href = "Infos.html";
        contactsA.innerText = "Ansprechpartner";
        let contactsLi = document.createElement("li");
        contactsLi.id = "Ansprechpartner";
        contactsLi.appendChild(contactsA);
        let datesA = document.createElement("a");
        datesA.href = "Infos.html";
        datesA.innerText = "Termine";
        let datesLi = document.createElement("li");
        datesLi.id = "Termine";
        datesLi.appendChild(datesA);
        let requirementsA = document.createElement("a");
        requirementsA.href = "Infos.html";
        requirementsA.innerText = "Anforderungen";
        let requirementsLi = document.createElement("li");
        requirementsLi.id = "Anforderungen";
        requirementsLi.appendChild(requirementsA);
        let infosUl = document.createElement("ul");
        infosUl.classList.add("dropdown-content");
        infosUl.appendChild(historyLi);
        infosUl.appendChild(contactsLi);
        infosUl.appendChild(datesLi);
        infosUl.appendChild(requirementsLi);
        let infosDiv = document.createElement("div");
        infosDiv.classList.add("drop");
        infosDiv.appendChild(infosLi);
        infosDiv.appendChild(infosUl);
        //Navigation Blog
        let blogA = document.createElement("a");
        blogA.classList.add("mI_Text");
        blogA.href = "Blog.html";
        blogA.innerText = "Blog";
        let blogLi = document.createElement("li");
        blogLi.classList.add("mainItem");
        blogLi.id = "Blog";
        blogLi.appendChild(blogA);
        let rundspruecheA = document.createElement("a");
        rundspruecheA.href = "Blog.html";
        rundspruecheA.innerText = "Rundsprüche";
        let rundspruecheLi = document.createElement("li");
        rundspruecheLi.id = "Rundspruche";
        rundspruecheLi.appendChild(rundspruecheA);
        let latestA = document.createElement("a");
        latestA.href = "Blog.html";
        latestA.innerText = "Aktuell";
        let latestLi = document.createElement("li");
        latestLi.id = "Aktuell";
        latestLi.appendChild(latestA);
        let archiveA = document.createElement("a");
        archiveA.href = "Blog.html";
        archiveA.innerHTML = "Archiv";
        let archiveLi = document.createElement("li");
        archiveLi.id = "Archiv";
        archiveLi.appendChild(archiveA);
        let rundspruecheUl = document.createElement("ul");
        rundspruecheUl.appendChild(latestLi);
        rundspruecheUl.appendChild(archiveLi);
        let forumA = document.createElement("a");
        forumA.href = "Blog.html";
        forumA.innerText = "Forum";
        let forumLi = document.createElement("li");
        forumLi.id = "Forum";
        forumLi.appendChild(forumA);
        let blogUl = document.createElement("ul");
        blogUl.classList.add("dropdown-content");
        blogUl.appendChild(rundspruecheLi);
        blogUl.appendChild(rundspruecheUl);
        blogUl.appendChild(forumLi);
        let blogDiv = document.createElement("div");
        blogDiv.classList.add("drop");
        blogDiv.appendChild(blogLi);
        blogDiv.appendChild(blogUl);
        //Navigation Certificates
        let certificatesA = document.createElement("a");
        certificatesA.classList.add("mI_Text");
        certificatesA.href = "Certificates.html";
        certificatesA.innerText = "Diplome";
        let certificatesLi = document.createElement("li");
        certificatesLi.classList.add("mainItem");
        certificatesLi.id = "Diplome";
        certificatesLi.appendChild(certificatesA);
        let insertA = document.createElement("a");
        insertA.href = "Certificates.html";
        insertA.innerText = "Diplombeilage";
        let insertLi = document.createElement("li");
        insertLi.id = "Diplombeilage";
        insertLi.appendChild(insertA);
        let certificatesUl = document.createElement("ul");
        certificatesUl.classList.add("dropdown-content");
        certificatesUl.appendChild(insertLi);
        let certificatesDiv = document.createElement("div");
        certificatesDiv.classList.add("drop");
        certificatesDiv.appendChild(certificatesLi);
        certificatesDiv.appendChild(certificatesUl);
        //Navigation Contests
        let contestsA = document.createElement("a");
        contestsA.classList.add("mI_Text");
        contestsA.href = "Contests.html";
        contestsA.innerText = "Contests";
        let contestsLi = document.createElement("li");
        contestsLi.classList.add("mainItem");
        contestsLi.id = "Contests";
        contestsLi.appendChild(contestsA);
        let resultsA = document.createElement("a");
        resultsA.href = "Contests.html";
        resultsA.innerText = "Ergebnisse";
        let resultsLi = document.createElement("li");
        resultsLi.id = "Ergebnisse";
        resultsLi.appendChild(resultsA);
        let contestsUl = document.createElement("ul");
        contestsUl.classList.add("dropdown-content");
        contestsUl.appendChild(resultsLi);
        let contestsDiv = document.createElement("div");
        contestsDiv.classList.add("drop");
        contestsDiv.appendChild(contestsLi);
        contestsDiv.appendChild(contestsUl);
        //Navigation Members
        let membersA = document.createElement("a");
        membersA.classList.add("mI_Text");
        membersA.href = "Members.html";
        membersA.innerText = "Mitglieder";
        let membersLi = document.createElement("li");
        membersLi.classList.add("mainItem");
        membersLi.id = "Mitglieder";
        membersLi.appendChild(membersA);
        let becomeA = document.createElement("a");
        becomeA.href = "Members.html";
        becomeA.innerText = "Mitglied werden?";
        let becomeLi = document.createElement("li");
        becomeLi.id = "DIGwerden";
        becomeLi.appendChild(becomeA);
        let memberListA = document.createElement("a");
        memberListA.href = "Members.html";
        memberListA.innerText = "Mitgliederliste";
        let memberListLi = document.createElement("li");
        memberListLi.id = "Mitgliederliste";
        memberListLi.appendChild(memberListA);
        let departmentsA = document.createElement("a");
        departmentsA.href = "Members.html";
        departmentsA.innerText = "Sektionen";
        let departmentsLi = document.createElement("li");
        departmentsLi.id = "Sektionen";
        departmentsLi.appendChild(departmentsA);
        let membersUl = document.createElement("ul");
        membersUl.classList.add("dropdown-content");
        membersUl.appendChild(becomeLi);
        membersUl.appendChild(memberListLi);
        membersUl.appendChild(departmentsLi);
        let membersDiv = document.createElement("div");
        membersDiv.classList.add("drop");
        membersDiv.appendChild(membersLi);
        membersDiv.appendChild(membersUl);
        //Navigation Downloads
        let downloadsA = document.createElement("a");
        downloadsA.classList.add("mI_Text");
        downloadsA.href = "Downloads.html";
        downloadsA.innerText = "Downloads";
        let downloadsLi = document.createElement("li");
        downloadsLi.classList.add("mainItem");
        downloadsLi.id = "Downloads";
        downloadsLi.appendChild(downloadsA);
        let dowRulesA = document.createElement("a");
        dowRulesA.href = "Downloads.html";
        dowRulesA.innerText = "Diplomausschreibungen";
        let dowRulesLi = document.createElement("li");
        dowRulesLi.id = "Dow_Ausschreibungen";
        dowRulesLi.appendChild(dowRulesA);
        let dowResultsA = document.createElement("a");
        dowResultsA.href = "Downloads.html";
        dowResultsA.innerText = "Contestergebnisse";
        let dowResultsLi = document.createElement("li");
        dowResultsLi.id = "Dow_Ergebnisse";
        dowResultsLi.appendChild(dowResultsA);
        let dowGCRA = document.createElement("a");
        dowGCRA.href = "Downloads.html";
        dowGCRA.innerText = "GCR-Liste";
        let dowGCRLi = document.createElement("li");
        dowGCRLi.id = "Dow_GCR";
        dowGCRLi.appendChild(dowGCRA);
        let dowMemberListA = document.createElement("a");
        dowMemberListA.href = "Downloads.html";
        dowMemberListA.innerText = "Mitgliederliste";
        let dowMemberListLi = document.createElement("li");
        dowMemberListLi.id = "Dow_Mitgliederliste";
        dowMemberListLi.appendChild(dowMemberListA);
        let downloadsUl = document.createElement("ul");
        downloadsUl.classList.add("dropdown-content");
        downloadsUl.classList.add("right");
        downloadsUl.appendChild(dowRulesLi);
        downloadsUl.appendChild(dowResultsLi);
        downloadsUl.appendChild(dowGCRLi);
        downloadsUl.appendChild(dowMemberListLi);
        let downloadsDiv = document.createElement("div");
        downloadsDiv.classList.add("drop");
        downloadsDiv.appendChild(downloadsLi);
        downloadsDiv.appendChild(downloadsUl);
        DIG_main.mainNavUl = document.createElement("ul");
        DIG_main.mainNavUl.appendChild(infosDiv);
        DIG_main.mainNavUl.appendChild(blogDiv);
        DIG_main.mainNavUl.appendChild(certificatesDiv);
        DIG_main.mainNavUl.appendChild(contestsDiv);
        DIG_main.mainNavUl.appendChild(membersDiv);
        DIG_main.mainNavUl.appendChild(downloadsDiv);
    }
    DIG_main.addHeader_Navigation = addHeader_Navigation;
    function addHeader_mainNav(_screenType) {
        //main_NavElement
        let nav = document.createElement("nav");
        nav.id = "mainNav";
        nav.classList.add("item4");
        nav.classList.add("overlay");
        nav.appendChild(DIG_main.mainNavUl);
        if (_screenType == "vertical") {
            let smallStripeDiv = document.createElement("div");
            smallStripeDiv.id = "stripeNav";
            nav.appendChild(smallStripeDiv);
            nav.appendChild(flagDiv);
            DIG_main.header.appendChild(nav);
        }
        DIG_main.header.appendChild(nav);
        //MainStripe
        let stripeDiv = document.createElement("div");
        stripeDiv.id = "stripe";
        stripeDiv.classList.add("item5");
        DIG_main.header.appendChild(stripeDiv);
    }
    DIG_main.addHeader_mainNav = addHeader_mainNav;
})(DIG_main || (DIG_main = {}));
//# sourceMappingURL=header.js.map